### ISSUE TITLE
How do I add information to pages that are based off templates?

### ISSUE THREAD

**Issue by sudobeans** [MindustryGame/wiki#45]
To start off, I'm kind of a noob to GitHub/the game wiki/things like that. I was hoping to add more information on the power generators (e.g., "combustion generators work at 115% efficiency when you put spore pods in them"). 

However, the bottom of each md file in [wiki/docs](https://github.com/MindustryGame/wiki/tree/master/docs) says `(WARNING: Do not modify the text above. It is automatically generated every release.)` What is the best way to add information to these pages?

**Comment by Anuken** [comment]
If it's special text specific to a block, you can add it by adding text below the "do not edit" notice. In that specific, I don't think that's necessary information - instead of mentioning a specific item, you should explain how efficiency of combustion generators depends on the flammability of the input item.

The page generator for blocks is implemented [here](https://github.com/Anuken/Mindustry-Wiki-Generator/blob/master/src/wikigen/generators/BlockGenerator.java) ([template](https://github.com/Anuken/Mindustry-Wiki-Generator/blob/master/templates/block.md)).
